server:
  port: 8080

spring:
  application:
    name: gateway-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5

zuul:
  prefix: /api