server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:gateway-keystore.jks
    key-store-password: password

spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}

zuul:
  prefix: /api
  retryable: true

ribbon:
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 2
  ReadTimeout: 5000000
  ConnectTimeout: 5000000
  CustomSSLSocketFactoryClassName: com.netflix.http4.ssl.AcceptAllSocketFactory
  IsHostnameValidationRequired: false
  TrustStore: classpath:gateway-keystore.jks
  TrustStorePassword: password