server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: password

spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      retry:
        enabled: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    platform: org.hibernate.dialect.Oracle11gDialect
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: none

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8085/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}

zuul:
  prefix: /api
  retryable: true

ribbon:
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 2
  ReadTimeout: 5000000
  ConnectTimeout: 5000000
  CustomSSLSocketFactoryClassName: com.netflix.http4.ssl.AcceptAllSocketFactory
  IsHostnameValidationRequired: false


jwt:
  security:
    key: "secret"